### ISSUE TITLE
StandardVideoController (extends Activity)

### ISSUE THREAD

**Issue by incapdns** [cdnbye/android-p2p-engine#1]
ADB Logcat: https://pastebin.com/WnYX6xUp
Java file: https://pastebin.com/ssBpU4Cq
XML: https://pastebin.com/n5dKk1wq
Gradle: https://pastebin.com/Arf0bvcP

Note: The problem is in line 269 -> controller = new StandardVideoController(this);
Error: 
a) Caused by: android.view.InflateException: Binary XML file line #28: Error inflating class com.d
ueeeke.videocontroller.MarqueeTextView
b) Caused by: java.lang.ClassNotFoundException: Didn't find class "com.dueeeke.videocontroller.Mar
queeTextView" on path: DexPathList[[zip file "/data/app/io.p2p.iptv-1/base.apk"],nativeLibraryDirectories=[/data/app/io.
p2p.iptv-1/lib/x86, /vendor/lib, /system/lib]]

I am using the same repository (this) to compile with just a few changes, thanks in advance and waiting for answers.

**Comment by snowinszu** [comment]
The demo is updated, please update your code.

**Comment by incapdns** [comment]
Thanks, now is working fine.
