### ISSUE TITLE
Cannot play DASH live

### ISSUE THREAD

**Issue by hungdx6** [cdnbye/android-p2p-engine#10]
Hello dev team,

I'm testing your project and I found that the SDK cannot play DASH live streams. I'm playing an custom stream and It cannot under stand the tag SegmentTemplate  like:

```
<SegmentTemplate timescale="48000" initialization="BigBuckBunny-$RepresentationID$.dash" media="BigBuckBunny-$RepresentationID$-$Time$.dash">
    <SegmentTimeline>
          <S t="77918892747742" d="96256" r="1"/>
          <S d="95232"/>
          <S d="96256" r="2"/>
          <S d="95232"/>
          <S d="96256" r="2"/>
          <S d="95232"/>
          <S d="96256" r="2"/>
          <S d="95232"/>
    </SegmentTimeline>
</SegmentTemplate>

```
Currently, the SDK can just play the VOD by sends a segment base request and receives Content-Range header response from the server. Server responses Content-Range with the size of the whole VOD program, then the SDK can understand. But in DASH live, the program is consist of multiple segments and use SegmentTemplate  to describe the chunks file name. Please support DASH LIVE.

**Comment by snowinszu** [comment]
Hi, could you offer a test stream so we can reproduce the bug, thanks!

**Comment by hungdx6** [comment]
Hi, my server is in internal network so I cannot give you the link. Instead, you can use Peer5 demo stream to test, they have DASH live with SegmentTemplate : https://wowza.peer5.com/live/smil:bbb_abr.smil/manifest.mpd

The player can just download the first chunk, then it stops.

**Comment by snowinszu** [comment]
I play this stream, and it works well

**Comment by snowinszu** [comment]
Which version of sdk do you use?

**Comment by hungdx6** [comment]
I use 2.4.1 version, but I changed player to Bitmovin. After use your original code, the player is ok. But in my case, the proxy just repeatly requests the init chunk. I think my code have some error and trying to debug. Thank you.
