### ISSUE TITLE
Record Live Stream M3U8 (For Playback)

### ISSUE THREAD

**Issue by incapdns** [cdnbye/android-p2p-engine#2]
Your service works perfectly well, if you can help me implement a "record" function or send a external reference link where I can do it.

Because the videos are displayed in WebRTC (P2P) and HTTP (Server), is it possible to "record" the content to watch later in "playback"?

Note: I'm using com.dueeeke.videoplayer due to the design (I was able to solve the display problem)

Thanks in advance.

**Comment by snowinszu** [comment]
https://exoplayer.dev/downloading-media.html

**Comment by incapdns** [comment]
Sorry for the delay in answering, could you show me an example code?
I am this: https://pastebin.com/DQpcjWaa

**Comment by incapdns** [comment]
Problem solved.
I found that it is not possible to record only the videoview in specific
