### ISSUE TITLE
About traffic

### ISSUE THREAD

**Issue by rubensmesquita** [cdnbye/android-p2p-engine#4]
If I point everything to my servers in the case of stun, signal, trackers will I still need to hire traffic even though nothing is going on your servers?

**The question I have is this, even though everything is aimed at my servers, will I still need to hire traffic?**

**Comment by ceelsoin** [comment]
I need the same question

**Comment by snowinszu** [comment]
Hi,
    Android SDK is free for the whole year in 2020.
