### ISSUE TITLE
Error com.cdnbye.core.download .

### ISSUE THREAD

**Issue by Ramys** [cdnbye/android-p2p-engine#9]
I'm compiling this apk, but I came across this error.

android-p2p-engine\app\src\main\java\com\cdnbye\p2pengine\DownloadActivity.java:10: error: package com.cdnbye.core.download does not exist.

**Comment by snowinszu** [comment]
Download the latest version SDK(https://cdnbye.oss-cn-beijing.aliyuncs.com/android_sdk/cdnbye-2.2.3.jar)，then copy it to app/libs .

**Comment by Ramys** [comment]
> Download the latest version SDK([https://cdnbye.oss-cn-beijing.aliyuncs.com/android_sdk/cdnbye-2.2.3.jar)，then](https://cdnbye.oss-cn-beijing.aliyuncs.com/android_sdk/cdnbye-2.2.3.jar)%EF%BC%8Cthen) copy it to app/libs .

Worked perfectly.
Thanks for the support!
